### ISSUE TITLE
引入mpvue中什么也没有显示

### ISSUE THREAD

**Issue by FxPixels** [wxa-component/wxa-comp-canvas-drag#3]
`properties: {
        graph: {
            type: Object,
            value: {},
            observer: 'onGraphChange',
        },
}`

一开始报 onGraphChange 中 this.drawArr 错误 所以也就无法 push ，props传过去 graph:{}，我猜测mpvue 会把 {} 变成 null 
于是在 onGraphChange 中加上判断 

`if (JSON.stringify(n) === '{}' || JSON.stringify(n) === 'null') return;`
加了这一句

然后就没有然后了，错也没有报，不知道怎么搞…

**Comment by lineezhang** [comment]
你最后解决了吗，我也遇到相同问题

**Comment by FxPixels** [comment]
> 你最后解决了吗，我也遇到相同问题

我已经没有做小程序了，原公司都倒闭了，都还没有解决…
可以考虑尽早脱离mpvue苦海…用原生没有这么多麻烦。
